name: Portfolio

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    
    - name: checkout code
      uses: actions/checkout@v1
    - name: SetupNode.js environment
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Test 
      run: npm test
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1
    - name: Deploy static site to S3 bucket
      run: aws s3 sync s3://git-action-portfolio --delete
    
